# PostgreSQL Profile Configuration
spring:
  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: GAon@#$%12
  
  # JPA Configuration for PostgreSQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        envers:
          audit_table_suffix: _audit
          revision_field_name: rev
          revision_type_field_name: revtype
          store_data_at_delete: true
          default_schema: public
          default_catalog: public
  
  # H2 Console disabled for PostgreSQL
  h2:
    console:
      enabled: false
